# Generated by Django 5.0.7 on 2024-07-22 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EducationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('has_program', models.BooleanField()),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WhoIsThisProgramFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('icon', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='DirectionFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.faq')),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('cover_image', models.URLField()),
                ('tuition_fee', models.IntegerField()),
                ('prices', models.IntegerField()),
                ('period', models.CharField(max_length=255)),
                ('education_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.educationtype')),
            ],
        ),
    ]
